### ISSUE TITLE
Missing files. Unable to compile.

### ISSUE THREAD

**Issue by Ondalf** [GALE-forkbeard/Galleoncoin#1]
This issue tracker is only for technical issues related to GalleonCoin Core.
General GalleonCoin questions and/or support requests and are best directed to the [GalleonCoin Discord](https://discord.galleoncoin.org).

### Describe the issue
Simply unable to compile. Missing files

#### If so, please list the steps to reproduce below:
1. git clone this repo
2. autoreconf -fi
3. ./configure && make

### Expected behavior
This program to compile

### Actual behavior
Missing json files that are included in few .cpp files

### What version of GalleonCoin Core are you using?
Initial commit

### Machine specs:
Irrelevant

### Any extra information that might be useful in the debugging process.
Missing files:
src/zgale/accumulatorcheckpoints.json.h
src/invalid_outpoints.json.h
src/invalid_serials.json.h

**Comment by le2Ks** [comment]
Hello,

Please refer to the two following commits which fix the compiling issue:
https://github.com/GALE-forkbeard/Galleoncoin/commit/f73562b3cd7f87b1dbbf0eca60c2f5957629578a
https://github.com/GALE-forkbeard/Galleoncoin/commit/a49de9edf79ffc520206bef8dc0bbe2f4a1a85e9

Use the latest version v1.1.0 to also have all the last commits, including the qt's changes.
https://github.com/GALE-forkbeard/Galleoncoin/releases/tag/v1.1.0

Thank you!

**Comment by le2Ks** [comment]
Closing the issue. Let us know if you have any further questions :).
