### ISSUE TITLE
SCAMMER ALERT

### ISSUE THREAD

**Issue by Micenas** [GALE-forkbeard/Galleoncoin#2]
this "Developer" is a scammer, he hired me to made the web wallet, which i made and he didnt pay me, and ran off with the final product.
His coin was made by another hired developer on Fiverr, He does not know what he's doing.

**Comment by GALE-forkbeard** [comment]
The disgruntled young man above blocked his "After sales" support thread after consistently trying to upsell us and taking over 48 hours to provide "solutions" that did nothing to change the fact that both properties he was responsible for failed to remain stable. 

The "Final products" on the server had to nuked and reinstalled, so, no, the team gained nothing out of our exchange with the individual above. 

Young man, I gently remind you that at this stage of your career, the last thing you want to do is have a reputation as the sort of person who runs around smearing excreta on anyone dissatisfied with the quality of your work. 

We wish you the best of luck in your future endeavors.
